# Yarn Mapping
- repository: https://maven.fabricmc.net
  groupId: net.fabricmc
  artifactId: yarn
  version: "${mcVersion}+*"
  properties:
    yarn_mappings:
      source: version
# Fabric Loader
- repository: https://maven.fabricmc.net
  groupId: net.fabricmc
  artifactId: fabric-loader
  version: "*"
  properties:
    loader_version:
      source: version
# Fabric API
- repository: https://maven.fabricmc.net
  groupId: net.fabricmc.fabric-api
  artifactId: fabric-api
  version: "*+${mcVersion}"
  properties:
    fabric_version:
      source: version

# Mod Menu
- repository: https://api.modrinth.com/maven
  groupId: maven.modrinth
  artifactId: modmenu
  version: "11.*"
  properties:
    mod_menu_version:
      source: version
