name: Test Build
on: [push, pull_request]

env:
  JAVA_VERSION: 17 # must be the same as the version used in build.gradle
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build
        id: build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
